# Generated by Django 3.1.2 on 2020-10-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='propic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
